### ISSUE TITLE
[RFE] Should be able to bootstrap with puppet 3 and puppet 4

### ISSUE THREAD

**Issue by zjhuntin** [Katello/katello-client-bootstrap#105]
As we are moving closer to integrating puppet 4 into Katello it would be good to have this also be able to boot strap systems with puppet 4.

**Comment by evgeni** [comment]
@zjhuntin totally agree. are you aware of any needed changes for that? did puppet.conf syntax change?

**Comment by sideangleside** [comment]
Closing this as bootstrap now supports puppet4 now that #230 has been merged.
