### ISSUE TITLE
bootstrap.py katello-ca-consumer rpm fails if it already installed 

### ISSUE THREAD

**Issue by sean797** [Katello/katello-client-bootstrap#119]
If you run ./bootstrap.py and the katello-ca-consumer rpm is already installed it fails :-1:

**Comment by sideangleside** [comment]
that is by design. If you run bootstrap with the `--force` switch, it will remove the existing RPM and reinstall it.

**Comment by sean797** [comment]
Thanks @sideangleside!

**Comment by sideangleside** [comment]
I think it is reasonable for bootstrap to have a better failure message in this scenario to inform the user of the `--force` option. You aren't the first user to ask/notice. Reopening this issue so that it can be addressed.
