### ISSUE TITLE
Not real hostname are used

### ISSUE THREAD

**Issue by peppos** [Katello/katello-client-bootstrap#126]
When in my /etc/hosts exist many entries with same ip, the bootstrap.py use the first entry and not a real hostname and domain from "hostname -f". I saw that part of the script that values the variables is this:

```
FQDN = socket.getfqdn()
    if FQDN.find(".") != -1:
        HOSTNAME = FQDN.split('.')[0]
        DOMAIN = FQDN[FQDN.index('.') + 1:]
    else:
        HOSTNAME = FQDN
        DOMAIN = None
```
Is possible to change this for use a real hostname from hostname -f for example?

**Comment by evgeni** [comment]
Hey @peppos, thanks for the report!

I would really prefer to keep a pure Python solution (read `socket.getfqdn()`) instead of calling an external binary. I am not even sure if having the same IP adress in `/etc/hosts` is properly defined.

Could you please post the content of `/etc/hosts` and the outputs of `hostname`, `hostname -s`, `hostname -f`, `python --version` and `python -c 'import socket; print socket.getfqdn(); print socket.gethostname()'`?

Feel free to anonymize the output, if it contains anything you want to keep internal, as long as it is still consistent with the real output you get.

Thanks

**Comment by peppos** [comment]
Hi @evgeni, thanks for your reply.
here is the information required:

```
[root@myserver ~]# cat /etc/hosts
10.1.1.1     aaa   aaa.newdomain.com
10.1.1.1     bbb   bbb.newdomain.com
10.1.1.1     cccc   cccc.newdomain.com
10.1.1.1     dddd   dddd.newdomain.com
10.1.1.1     eeee   eeee.newdomain.com
10.1.1.1     fffff   fffff.newdomain.com
10.1.1.1     ggggg   ggggg.newdomain.com

10.1.1.1     hhhh   hhhh.newdomain.com
10.1.1.1     iiiii   iiiii.newdomain.com

#127.0.0.1              myserver localhost.localdomain localhost
127.0.0.1               localhost.localdomain localhost
::1             localhost6.localdomain6 localhost6
10.1.1.1             myserver.mydomain.domain.it myserver

[root@myserver ~]# hostname
myserver
[root@myserver ~]# hostname -s
myserver
[root@myserver ~]# hostname -f
myserver.mydomain.domain.it

[root@myserver ~]# python -V
Python 2.4.3

[root@myserver ~]# python -c 'import socket; print socket.getfqdn(); print socket.gethostname()'
aaa.newdomain.com
myserver
```

**Comment by evgeni** [comment]
Related @ansible issue: https://github.com/ansible/ansible/issues/9972 (related as it is also using `socket.getfqdn()`)

**Comment by evgeni** [comment]
Downstream (Satellite) BZ https://bugzilla.redhat.com/show_bug.cgi?id=1361339

**Comment by evgeni** [comment]
I've been talking to @sideangleside about adding a way to override the FQDN detection via a command line parameter, I think this is as good as we can get here without doing any nasty hacks.

**Comment by sideangleside** [comment]
@peppos take a look at #164, this implements the `--override-fqdn` option that @evgeni and I were discussing.

**Comment by sideangleside** [comment]
#164 is merged, and provides now the `--fqdn` option. From the [README](https://raw.githubusercontent.com/Katello/katello-client-bootstrap/master/README.md) 

Many users have either hostnames that are short (`hostname -f` or python's `socket.getfqdn` returns a hostname that isn't an FQDN) or non-RFC compliant (containing a character such as an underscore `_` which fails Foreman's hostname validation.

In many cases, the user cannot update his/her system to provide a FQDN. bootstrap.py provides the `--fqdn` which allows the user to specify the FQDN that will be reported to Foreman

**Prerequisites**

The user needs to set to **False** the `create_new_host_when_facts_are_uploaded` and ` create_new_host_when_reports_are_uploaded` options. If these options are not set, a host entry will be created based upon the facts provided by facter.  This can be done with hammer.

~~~
hammer settings set \
  --name  create_new_host_when_facts_are_uploaded \
  --value false
hammer settings set \
  --name  create_new_host_when_reports_are_uploaded \
  --value false
~~~

Example Usage
~~~
# hostname -f
node-100

# python -c 'import socket; print socket.getfqdn()'
node-100

# ./bootstrap.py -l admin \
    -s foreman.example.com \
    -o "Red Hat" \
    -L RDU \
    -g "RHEL7/Crash" \
    -a ak-Reg_To_Crash \
    --fqdn node-100.example.com
