### ISSUE TITLE
This script seems very broken for Satellite 6.1

### ISSUE THREAD

**Issue by dgersting** [Katello/katello-client-bootstrap#13]
Satellite 6.1 returns the following error to the "Create Host" API call:

```
{
    "error": {
        "id": null,
        "errors": {
            "environment_id": [
                "can't be blank"
            ],
            "architecture_id": [
                "can't be blank"
            ],
            "operatingsystem_id": [
                "can't be blank"
            ],
            "domain_id": [
                "can't be blank"
            ],
            "root_pass": [
                "should be 8 characters or more",
                "should not be blank - consider setting a global or host group default"
            ],
            "ptable_id": [
                "can't be blank unless a custom partition has been defined"
            ]
        },
        "full_messages": [
            "Environment can't be blank",
            "Architecture can't be blank",
            "Operatingsystem can't be blank",
            "Domain can't be blank",
            "Root password should be 8 characters or more",
            "Root password should not be blank - consider setting a global or host group default",
            "Partition Table can't be blank unless a custom partition has been defined"
        ]
    }
}
```

Since some of these params are not present in the Satellite 6.0 API Guide, it's my assumption that they were added in 6.1 (though I can't confirm this as Red Hat's 6.1 API Guide appears incomplete/broken.

This also seems related to this Red Hat bug: https://bugzilla.redhat.com/show_bug.cgi?id=1135651

**Comment by evgeni** [comment]
Hey @dgersting, I usually would expect these params to be set on the hostgroup level. And they were mandatory in Satellite 6.0 already, so there is no Sat 6.1 change that is causing this.

Greets

**Comment by Rocco83** [comment]
@dgersting i think that the bug has some private information, i see that as reopened but no other information. I think i have, in satellite 6.1.6, the documentation written properly.
Are you able to check it on your side?
In any case is https://github.com/sideangleside/sat6-bootstrap/pull/35 fixing your problem?

**Comment by evgeni** [comment]
no update for a long time → closing.

feel free to reopen if the issue persists.
