### ISSUE TITLE
systemctl / chkconfig

### ISSUE THREAD

**Issue by bergsjoh** [Katello/katello-client-bootstrap#142]
In install_katello_agent and install_puppet_agent bootstrap is using chkconfig.

In some cases (where you might run automation, with non-full environments etc) you will end up with errors due to chkconfig redirection to systemctl on RHEL7 doesn't work.

Proposed fix: Run systemctl commands for rhel7, chkconfig for < rhel7.

**Comment by evgeni** [comment]
In which environment would that not work?

Quick check on a EL7 machine yields:
```
[root@localhost ~]# chkconfig postfix on
Note: Forwarding request to 'systemctl enable postfix.service'.
Created symlink from /etc/systemd/system/multi-user.target.wants/postfix.service to /usr/lib/systemd/system/postfix.service.
[root@localhost ~]# chkconfig postfix off
Note: Forwarding request to 'systemctl disable postfix.service'.
Removed symlink /etc/systemd/system/multi-user.target.wants/postfix.service.
```

So yeah, we could add an if/else to the right places, to make the code clearer. But it should work already today.

**Comment by bergsjoh** [comment]
We encountered issues with this due to crappy automation tools. I worked around it, was basically a suggestion for cleanup, not a bug in bootstrap, but rather my tools around it.

**Comment by alosadagrande** [comment]
+1. Same error due to automation tool.
