### ISSUE TITLE
Creation of /etc/rhsm/facts/katello.facts fails on systems that do not have subscription-manager installed

### ISSUE THREAD

**Issue by sideangleside** [Katello/katello-client-bootstrap#143]
On older systems that do not have subscription-manager (or on systems where the admin never installed it), the creation of `/etc/rhsm/facts/katello.facts fails` with a traceback similar to the following:

~~~
Traceback (most recent call last):
  File "./bootstrap.py.orig", line 797, in <module>
    clean_environment()
  File "./bootstrap.py.orig", line 277, in clean_environment
    katellofacts = open('/etc/rhsm/facts/katello.facts', 'w')
IOError: [Errno 2] No such file or directory: '/etc/rhsm/facts/katello.facts'
~~~

This is because `/etc/rhsm/facts` is created (and owned) by the subscription-manager package and doesn't exist until after the package is installed. 

We can address this one of two ways. 

- run the pythonic equivalent of `mkdir -p /etc/rhsm/facts` in the `clean_environment` function. 
- move the code that creates `/etc/rhsm/facts/katello.facts` to run after subscription-manager is installed in the `install_prereqs` function. 

See also [RH BZ1408972 ](https://bugzilla.redhat.com/show_bug.cgi?id=1408972)

**Comment by evgeni** [comment]
I'd prefer to move the facts creation after the installation of sub-man.

**Comment by dLobatog** [comment]
Submitted patches for both solutions, feel free to close whichever is not merged
