### ISSUE TITLE
Satellite complains about blank IP during host entry creation

### ISSUE THREAD

**Issue by Tontonitch** [Katello/katello-client-bootstrap#146]
Hello,

I'm trying your script to add existing servers into our Satellite (6.2.5).
I have an issue, as the script fails at the host entry creation as Satellite complains about blank ip.
Please note that we use static IPs for servers, so no dhcp.
```
[...]
[RUNNING], [2017-01-04 17:20:21], [Calling Foreman API to create a host entry associated with the group & org]
url: https://xxxxx:443/api/v2/hosts/
method: POST
data: {
  "host": {
    "managed": "true",
    "name": "server1",
    "hostgroup_id": 8,
    "organization_id": 1,
    "mac": "xx:xx:xx:xx:xx:xx",
    "architecture_id": 1,
    "location_id": 2,
    "domain_id": 1
  }
}
An error occured: HTTP Error 422: Unprocessable Entity
url: https://xxxxx6:443/api/v2/hosts/
code: 422
data: {
  "host": {
    "managed": "true",
    "name": "server1",
    "hostgroup_id": 8,
    "organization_id": 1,
    "mac": "xx:xx:xx:xx:xx:xx",
    "architecture_id": 1,
    "location_id": 2,
    "domain_id": 1
  }
}
error: {
  "error": {
    "errors": {
      "interfaces.ip": [
        "can't be blank"
      ]
    },
    "id": null,
    "full_messages": [
      "Ip can't be blank"
    ]
  }
}
```
BR,
Yannick

**Comment by Tontonitch** [comment]
tested forcing jsondata with the ip setting
`    538     jsondata['host']['ip'] = 'xxx.xxx.xxx.xxx'`

it works

**Comment by evgeni** [comment]
Hey,

what is the subnet definition of the default subnet for hostgroup with id 8?

**Comment by Tontonitch** [comment]
```
[root@xxxx~]# hammer hostgroup info --id=8
Id:                     8
Name:                   HG_RHEL7-SOE-PROD
Title:                  HG_RHEL7-SOE/HG_RHEL7-SOE-PROD
[...]
Parent Id:              3
[root@xxxx~]#
```
```
[root@xxxx~]# hammer hostgroup info --id=3
Id:                     3
Name:                   HG_RHEL7-SOE
Title:                  HG_RHEL7-SOE
Operating System:       RedHat 7.3
[...]
Subnet:                 DC subnet
[...]
[root@xxxx~]# 
```
```
[root@xxxx~]# hammer subnet info --id=1
Id:            1
Name:          DC subnet
Network:       10.30.0.0
Mask:          255.255.0.0
[...]
[root@xxxx~]# 
```

**Comment by evgeni** [comment]
Now you ommited the most interesting part, I was looking for the DHCP and IPAM entries.

**Comment by Tontonitch** [comment]
Ok, hereunder:
DHCP:          satelliteserver.mydomain (https://satelliteserver.mydomain:9090)
IPAM:          None

Boot mode is also set to "Static".
The DHCP seems to be enabled on the Capsule, but is in fact not used.

**Comment by Tontonitch** [comment]
Hi Evgeni,

For your info, I added a --ip option to my katello-client-bootstrap fork.
https://github.com/Tontonitch/katello-client-bootstrap/commit/f1296ac89c3756af4c9ec8517dc6de420e479021
I would say it is quick and dirty, and it would be better if the script would detect automatically the IP matching the detected MAC address. But at least it works.

Best regards,
Yannick

**Comment by evgeni** [comment]
Hey Yannick,

makes sense, yeah. Another solution would be to call bootstrap with `--unmanaged`.

I'll try to look into this some time next week, but I think your commit is a good start for now.

@sideangleside thoughts on that?

**Comment by evgeni** [comment]
scratch next week, can you try https://github.com/evgeni/katello-client-bootstrap/tree/ip?
this is your `--ip` plus some code to find an IP if none was passed

**Comment by Tontonitch** [comment]
Hi Evgeni,
It works perfectly now, using or not the --ip option. 
Thanks!
Yannick

**Comment by evgeni** [comment]
Closing after #165 has been merged and I (again) forgot to add the proper "Fixes" to the commit msg ;)

**Comment by mccun934** [comment]
As a reminder to myself and others hitting this, make sure the domain of the host you are bootstrapping is the **same** as the domain of the Host Group you are assigning it to.

**Comment by evgeni** [comment]
@mccun934 bootstrap should detect the domain of the host and set the domain_id accordingly. So the HG domain should not be used.
