### ISSUE TITLE
--legacy-purge

### ISSUE THREAD

**Issue by gearboxscott** [Katello/katello-client-bootstrap#148]
Maybe I'm reading this wrong but this is supposed to remove it from the satellite 5 server correct?   We just tried it and it didn't make a api call the sat5 server to remove the host after it registered it with the new sat6 server.    Looking at the source, doesn't seem like this has been added to the code yet?   Is that right?    -Scott

**Comment by sideangleside** [comment]
The purpose of the migrate_systems function is that if the system is registered to Satellite 5, RHN Classic, it'll call rhn-migrate-classic-to-rhsm to perform the migration. When --legacy-purge is passed, it'll remove the profile. (assuming the username/password provided is correct). Example (that I just ran on a system):

~~~
./bootstrap.py -v -s \
  satellite.example.com \
  -o Example \
  -a ak_Reg_To_Dev_EL7 \
  --skip-foreman \
  --legacy-login admin \
  --legacy-password [REDACTED] \
  --legacy-purge
~~~

In the above, I provided --legacy-password interactively, but the script will prompt for the password if omitted. How did you invoke the script? What version of the script are you running? and what output did it give you (to confirm/deny that it is doing  the right thing).

**Comment by evgeni** [comment]
Ping @gearboxscott?

I have successfully moved about 6k hosts using bootstrap from sat5 to 6, all using --legacy-purge.
So the feature is working as @sideangleside describes.

Can we please have some debugging info from your env?

**Comment by evgeni** [comment]
Ping @gearboxscott?

**Comment by evgeni** [comment]
Closing after no input. Please re-open if needed.
