### ISSUE TITLE
force non-migration codepath while systemdid is present

### ISSUE THREAD

**Issue by evgeni** [Katello/katello-client-bootstrap#151]
there are hosts that have a systemid file, but are not really regged to sat5
rhn-channel -l will take 30 seconds (timeout) to recognize that and go to the register path

maybe we should add --force-new-registration that skips the systemdid check at all and calls the rhn_cleanup?

**Comment by sideangleside** [comment]
Yes. Though I'd wonder if there is a better (and quicker) way to determine if a client is *properly* registered to RHN/Sat5.

**Comment by evgeni** [comment]
I am not old enough to know that. Thankfully.

**Comment by evgeni** [comment]
see https://github.com/evgeni/katello-client-bootstrap/tree/modular-skip for a possible solution
