### ISSUE TITLE
Missing closing bracket

### ISSUE THREAD

**Issue by enricomingardo** [Katello/katello-client-bootstrap#160]
```
./bootstrap.py
  File "./bootstrap.py", line 180
    curl_config.write("insecure")
              ^

```
due to a missing closing bracket at the end of the line
https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L179

**Comment by evgeni** [comment]
isn't it rather one opening bracket too much?

**Comment by enricomingardo** [comment]
OOOPs ;-)

**Comment by evgeni** [comment]
Technically, your code was still correct, as Python is a bit funny about single-element tuples:

```python
>>> "foo" == ("foo")
True
>>> "foo" == ("foo",)
False
```
