### ISSUE TITLE
Bootstrap fails on systems with a non-stock GEM_PATH environmental variable

### ISSUE THREAD

**Issue by sideangleside** [Katello/katello-client-bootstrap#166]
Running bootstrap.py against a Red Hat Cloudforms 4.2 installation fails with the following:

~~~
[NOTIFICATION], [2017-02-26 14:21:15], [Running Puppet in noop mode to generate SSL certs] 
[NOTIFICATION], [2017-02-26 14:21:15], [Visit the UI and approve this certificate via Infrastructure->Capsules] 
[NOTIFICATION], [2017-02-26 14:21:15], [if auto-signing is disabled] 
[RUNNING], [2017-02-26 14:21:15], [/usr/bin/puppet agent --test --noop --tags no_such_tag --waitforcert 10] 
[ERROR], [2017-02-26 14:21:16], EXITING: [/usr/bin/puppet agent --test --noop --tags no_such_tag --waitforcert 10] failed to execute properly.
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json/pure (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /opt/rh/rh-ruby23/root/usr/share/gems/gems/json-2.0.2/lib/json.rb:61:in `rescue in <module:JSON>'
	from /opt/rh/rh-ruby23/root/usr/share/gems/gems/json-2.0.2/lib/json.rb:58:in `<module:JSON>'
	from /opt/rh/rh-ruby23/root/usr/share/gems/gems/json-2.0.2/lib/json.rb:55:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'

~~~

Running `gem environment` on the node shows

~~~
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/rh/rh-ruby23/root/usr/local/share/gems
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby
  - RUBY EXECUTABLE: /opt/rh/rh-ruby23/root/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/rh/rh-ruby23/root/usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc/opt/rh/rh-ruby23
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /opt/rh/rh-ruby23/root/usr/local/share/gems
     - /opt/rh/cfme-gemset
     - /root/.gem/ruby
     - /opt/rh/rh-ruby23/root/usr/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /opt/rh/v8314/root/usr/bin
     - /opt/rh/nodejs010/root/usr/bin
     - /opt/rh/cfme-gemset/bin
     - /opt/rh/v8314/root/usr/bin
     - /opt/rh/rh-ruby23/root/usr/local/bin
     - /opt/rh/rh-ruby23/root/usr/bin
     - /opt/rh/rh-postgresql95/root/usr/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /opt/rh/rh-ruby23/root/usr/local/bin/
     - /root/bin
~~~

Compared to a stock RHEL7.3 system
~~~
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14.1
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/share/gems
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/share/gems
     - /root/.gem/ruby
     - /usr/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
~~~

un-setting the `GEM_PATH` environment variable allows the script to complete successfully (and is an easy enough patch if we choose to do it). The bigger question is what to do about ongoing puppet runs. I can see two _reasonable_ options. 

- Consider our work done since the system is registered and has completed a least one successful puppet run. Document the 'issue'
-  File an issue on the puppet agent so that it can ensure that it is using the correct GEM_PATH. 

There are other options like updating /usr/bin/puppet ourselves, but that is something that I'd seriously not entertain.

**Comment by evgeni** [comment]
Why is `rh-ruby23` even in the path?! Was this run from an `scl enable rh-ruby23 …`?
We could unset `GEM_PATH` as we do for `LD_PRELOAD` etc. But meh.

We also don't support running from a Python virtualenv which has no `rpm` module...

Edit: is this a CloudForms appliance node?

**Comment by sideangleside** [comment]
> Edit: is this a CloudForms appliance node?

Affirmative.  I pulled down the appliance and wanted to bootstrap it into my environment. Basically, I just downloaded the appliance, did some basic setup (IP/Hostname),  wget the bootstrap script, and attempted to register.

**Comment by evgeni** [comment]
Is using Puppet on those even supported?

Anyways:
* unsetting `GEM_PATH` will fix the bootstrap run, so that's fine for us.
* systemd will clean the env when starting the Puppet agent, so as long as the appliance is EL7 based, we're safe.
* any other combo I'd call not our problem ;)

**Comment by sideangleside** [comment]
Then I think we are good here. The appliances are all EL7 based & I've confirmed that systemd does what you've stated above, so ongoing puppet runs are working as expected.  PR incoming.
