### ISSUE TITLE
Add support for installing subscription-manager from the http kickstart repositories

### ISSUE THREAD

**Issue by mccun934** [Katello/katello-client-bootstrap#172]
For clients who do not have access to subscription-manager via a Spacewalk or Satellite 5 server, we should automatically attempt to hook into the freely available http based Kickstart repositories on the Katello/Satellite 6 server if synchronized.

This will streamline the bootstrap process and ensure subscription-manager is properly installed.

**Comment by sideangleside** [comment]
hitting `/katello/api/repositories` to get a list of repositories enabled in the org would work _but_ this wont work if `--skip foreman` is used since we dont grab username/password in that scenario.

**Comment by evgeni** [comment]
Well, even if `--skip foreman` is passed, the use *still* can also pass a username and a password for the Foreman API, we just don't enforce it.

There is one issue with the API approach: we have to do this *before* pulling the katello-ca-consumer RPM (as that requires sub-man), and without that RPM we don't know which API port to use.

We also have little chance to learn if the machine has really no access to a "proper" repo (think cloned channels, reposync'ed content etc), without `import yum` and then doing a search.

That all said, I love the idea and think we should add it :)

**Comment by sideangleside** [comment]
Can we just fix [bz1288817](https://bugzilla.redhat.com/show_bug.cgi?id=1288817)?

Though given the chicken-egg problems we have,  do we treat this is a semi-fatal error? 

Basically this workflow:

- user runs bootstrap.py
- bootstrap.py does a `import yum` and uses the requisite calls to 
  - check to see if the host already has `subscripton-manager` installed
  - check to see if `subscription-manager` is available in any configured repo. 
  - If yes, install it. 
  - If no, fail, and tell the user to provide the URL to a repo which provides `subscription-manager` using the new `--path-to-repo` (or whatever we want to name it) option.

**Comment by bergsjoh** [comment]
I'm providing a openly available (bootstrap) repo via satellite using reverse_proxy on capsules that supplies just this. Subscription-manager and the dependencies to solve the client issue of missing sub-man. We don't sync the kickstart repos as we don't provision servers using satellite.

**Comment by sideangleside** [comment]
So @bergsjoh, feel like testing #178 ? It should work with any HTTP yum repo. Yum might barf on an HTTPS repo if it isn't trusted.

**Comment by bergsjoh** [comment]
´Tested that PR, LGTM.
