### ISSUE TITLE
[RFE] Set Location on a host when using the --skip foreman option.

### ISSUE THREAD

**Issue by sideangleside** [Katello/katello-client-bootstrap#186]
As a user, when registering a host, I am using `--skip foreman` to register hosts without username/password as I am registering them for content only. I'd like the ability to set the host's location without needing a username / password

**Comment by sideangleside** [comment]
**Note:** you can set the `foreman_location` subscription-manager fact, prior to registration to accomplish this. 

~~~
cat /etc/rhsm/facts/location.facts 
{"foreman_location":"PHL"}
~~~

**Comment by alosadagrande** [comment]
Suggested workaround tested successfully on RH Satellite 6.2.10

**Comment by sideangleside** [comment]
Completed as part of #242
