### ISSUE TITLE
Deprecate old --skip-* options

### ISSUE THREAD

**Issue by evgeni** [Katello/katello-client-bootstrap#192]
Since we have the generic --skip method, we can deprecate --skip-puppet and --skip-foreman. First we should issue a warning and drop them in the next big release.

**Comment by sideangleside** [comment]
I thought you said we'd *NEVER* remove those options :) I guess we'd should probably start actually planning katello-client-bootstrap 2.0

**Comment by evgeni** [comment]
Never said that! :)
