### ISSUE TITLE
Define multiple capsules to copy ssh keys when enabling rex

### ISSUE THREAD

**Issue by alosadagrande** [Katello/katello-client-bootstrap#204]
When enabling remote execution (--rex) registered client downloads the foreman-proxy ssh key from the --server value defined. In case you have several capsules on the same location it is useful to allow to pass this information.

Could be useful to create a new parameter called --rex-capsules which overrides the --server value when added to boostrap.py. Also it should allow to enter comma separated values in case of multiple capsules at the same location.

**Comment by sideangleside** [comment]
Assuming we implement as designed, what is the failure mode: should we fail

- if we cannot download _any_ of the keys
- if we cannot download _all_ of the keys

Would a better solution be to allow the user to just provide an arbitrary URL which contains the public keys concatenated?

**Comment by alosadagrande** [comment]
Actually I already coded as I suggested at the beginning. Basically using the same function "install_foreman_ssh_key" looping each of the capsules passed by parameter (--rex-capsules). So taking a look at the function it just prints a warning / generic exception if cannot connect or if there is any problem. 

**/tools/scripts/satellite/bootstrap-wrapper.sh: [NOTIFICATION], [2017-08-29 15:56:01], [Could not reach the server. Error: [Errno 110] Connection timed out]** 
/tools/scripts/satellite/bootstrap-wrapper.sh: [NOTIFICATION], [2017-08-29 15:56:01], [Foreman's SSH key/s was/were added to /root/.ssh/authorized_keys] 
/tools/scripts/satellite/bootstrap-wrapper.sh: [NOTIFICATION], [2017-08-29 15:56:01], [Foreman's SSH key/s was/were added to /root/.ssh/authorized_keys] 



However as you suggested it makes now more sense to me to just create a concatenated file of all foreman's key ready to be imported. The aim of this issue is to solve the problem when more than one capsule is at the same location, probably they're behind a load balancer. In that case it will make sense to previously concatenate the keys and just call the load balancer VIP which will be in charge of retrieve the file from whatever capsule is online. If there is an offline capsule, we have to assume the LB is smart enough to route the call to the online one - otherwise would be a networking configuration problem ;) 

In my opinion the drawback is that you have to create the concatenated key yourself - out of the bootstrap.py. It's an easy task to automate and it's a one-time-shot, but must be taken into account.

I would suggest option called --rex-url-keys which would accept an http/https URI.
