### ISSUE TITLE
Define AuthorizedKeysFile path when rex is enable

### ISSUE THREAD

**Issue by alosadagrande** [Katello/katello-client-bootstrap#210]
There are some installations where AuthorizedKeysFile value is not the default one ($HOME/.ssh/authorized_keys). In thoses cases rex goes OK but obviously as the sshd is expecting the ssh pub keys in other directory, ssh with pubkey auth is failing.

**Comment by alosadagrande** [comment]
I have been taking a look and seems that there is no environment variable which can help us to locate the proper path for user's AuthorizedKeysFile.

I see two options:

1. Use regular expressions to extract the value from /etc/ssh/sshd_config file. Probably a if/else structure must be coded as well due to different values like: none, .ssh/authorized_keys, /etc/keys/%u/authorized_keys or even a single file 
2. Allow user to set this value during execution as --rex-authkey-path. Default value should be $HOME/.ssh/authorized_keys as it is already coded.

**Comment by evgeni** [comment]
I'd vote for 2. I hate guessing ;)

**Comment by sideangleside** [comment]
Same. +1 to option 2. (And I am afraid to ask who doesn't use the standard path for the AuthorizeKeysFile) :)

**Comment by evgeni** [comment]
I do, on boxes where I don't want the users to be able to change their keys.

**Comment by alosadagrande** [comment]
First time I see... but seems pretty reasonable from a security point of view.
