### ISSUE TITLE
Host params not available when re-registering host to capsule

### ISSUE THREAD

**Issue by dLobatog** [Katello/katello-client-bootstrap#214]
Host parameters added on the Host are lost after migrating the host from the Satellite to the Capsule.

Version-Release number of selected component (if applicable): 6.2.11
How reproducible: Always

Steps to Reproduce:
1.  Register a host with the Satellite, add puppet classes and host parameters on the host
2.  Re-register the host using the bootstrap.py to the Capsule.
3.  Check the "host Parameters" 

Actual results:
The host parameters which were previously added on the host are lost.

Expected results:
The Satellite should retain the parameters after migrating from Satellite to the capsule.

https://bugzilla.redhat.com/show_bug.cgi?id=1486760

**Comment by sideangleside** [comment]
This should be addressed by the work in #227

**Comment by sideangleside** [comment]
Closing as #227 has been merged.
