### ISSUE TITLE
Delete katello-host-tools and katello-host-tools-fact-plugin packages when unregistering

### ISSUE THREAD

**Issue by alosadagrande** [Katello/katello-client-bootstrap#222]
Unregistering a client running katello-agent 3.0 does not delete katello-host-tools either katello-host-tools-fact-plugin.

This is causing issues when moving a client running katello-agent 3.0 to katello-agent 2.9. Actually katello-agent 2.9 is not installed due to error in dependencies.

**Comment by alosadagrande** [comment]
Do you think we should check if katello-host-tools and/or katello-host-tools-fact-plugin are installed before calling yum erase on def clean_katello_agent():

call_yum("erase", "'katello-ca-consumer-*' katello-agent gofer 'katello-host-tools*' ")

**Comment by sideangleside** [comment]
yum skips non-existing packages so there is no need to have any 'if/then' logic. This would also be consistent with other places where we remove packages (https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L418)
