### ISSUE TITLE
Make bootstrap.py compatible with Puppet 4

### ISSUE THREAD

**Issue by h4xr** [Katello/katello-client-bootstrap#229]
Currently bootstrap.py fails if the client is trying to install puppet-agent for Puppet 4.
This seems to happen because of the change of the directory structure that is there with Puppet 4.

Puppet 3:
The configuration files live in /etc/puppet/puppet.conf
The executable is present in /usr/bin/puppet

Puppet 4:
The configuration file is in /etc/puppetlabs/puppet/puppet.conf
The executable is present in /opt/puppetlabs/puppet/bin/puppet

With the current version of bootstrap.py, it looks for the files according to Puppet 3 configuration and hence fails if the client is requesting for Puppet 4.

The question is should we detect the change in the puppet version inside bootstrap.py or allow the user to pass an option something like --install-puppet4 to handle this?

**Comment by evgeni** [comment]
I know, I initially proposed the `--puppet4` switch on IRC, but now that I thought about it more…

* the user might already have provided "the right" puppet version using content-views/activation-keys, so there is no need (and bad UX) to force them to pass the puppet version *again*
* there is no reliable way to do *all* the needed setup to get the right puppet packages (it's `puppet` vs `puppet-agent`, but we have no idea which repo we might have to enable).
* we have enough `--funny-switches` already, right @sideangleside?

So I think having a smart way to detect which puppet package was installed and acting accordingly is the way to go.

**Comment by sideangleside** [comment]
Correct. If anything, I'd rather an NVREA check against the package (since that is what we use to check versions of _other_ packages and would consistent. There is no need (IMHO) to add an additional switch for this.
