### ISSUE TITLE
[RFE] update bootstrap.py to only install katello-host-tools

### ISSUE THREAD

**Issue by sideangleside** [Katello/katello-client-bootstrap#251]
Katello [docs](https://theforeman.org/plugins/katello/nightly/installation/clients.html) recommend *not* installing katello-agent. bootstrap should do the same.

**Comment by gearboxscott** [comment]
I thought katello-agent was required for host-collection actions, errata to install now from the errata screen, package install, etc.  all these don't require remote execution to happen?
