### ISSUE TITLE
fips check

### ISSUE THREAD

**Issue by pgera** [Katello/katello-client-bootstrap#275]
/proc/sys/crypto/fips_enabled needn't exist. There should be a check between these two lines:

fips_file = open("/proc/sys/crypto/fips_enabled", "r")
fips_status = fips_file.read(1)

**Comment by sideangleside** [comment]
Are you stating that on your system that `/proc/sys/crypto/fips_enabled` doesn't exist on your system? 

What OS version are you running (on the client)?

**Comment by pgera** [comment]
It's a RHEL 7.5 system, but running the mainline kernel from elrepo's kernel-ml. /proc/sys/crypto/fips_enabled seems to be a feature of the downstream RHEL kernel.

**Comment by evgeni** [comment]
it does exist on my Fedora 29 box (4.19.5-300.fc29.x86_64), but yeah, I think we can still add a check for it.

**Comment by evgeni** [comment]
@pgera please test https://github.com/Katello/katello-client-bootstrap/pull/279
