### ISSUE TITLE
handling hostgroups without operating system and fields dependant on this field

### ISSUE THREAD

**Issue by Rocco83** [Katello/katello-client-bootstrap#31]
Hi,

I didn't ever faced the problem because of this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1306925

The problem is that 
- host[architecture_id](already fixed)
  optional , nil allowed  
  required if host is managed and value is not inherited from host group
- host[operatingsystem_id]
  optional , nil allowed  
  required if host is managed and value is not inherited from host group
- host[medium_id]
  optional , nil allowed  
  required if not imaged based provisioning and host is managed and value is not inherited from host group

Must be passed to API in order to not have a failure on the script.
I have already started writing the patch, creating the needed functions.

for post_json there are 2 ways to solve it, imo:
1) usage of json.append for each value not null
2) always filling json with optional data.

In option 2 i have not found how to do it properly.
passing null value in json will return error.

Any hint or suggestion on how to proceed?

Thanks,
Daniele

**Comment by sideangleside** [comment]
I am torn on how to solve this. What I am trying to avoid is having to have a function for every property of the host group that the user does not specify or is not inherited. Additionally, It is not assumed that the user running the bootstrap script is a/the Satellite administrator. I am OK with making the user have to set these fields on their hostgroup as mandatory.

**Comment by evgeni** [comment]
So I would also agree that the HG should be fully set-up and we should document this as a requirement. @Rocco83 's list also e.g. misses the root password, which also _has_ to be set ;-)

The current version already fetches the right arch-id from the API: https://github.com/sideangleside/sat6-bootstrap/blob/master/bootstrap.py#L376

OS-id and Medium-id is not really relevant as we are not _building_ the host anyways, so we could pass managed=false in the json and thus make all these fields non-required.

So my vote would be: document the requirements as they are at the moment plus add a "--dont-manage" switch to pass managed=false in the host create call.

**Comment by Rocco83** [comment]
Almost there with the patch :)
suggestion: --unmanaged instead of --dont-manage. the short option for "don't manage" is not clear, for unmanaged we can use -U.
feedback?

**Comment by Rocco83** [comment]
Hi,

https://github.com/Rocco83/sat6-bootstrap/commit/cb01fae1850e19e40e9f4b1ae7d69b3b709b53d9

Please check it and comment it.
I have also fixed other topics.

**Comment by evgeni** [comment]
nitpicks in PR :)

why did you move deleting to ID instead of FQDN -- this works fine here (but not opposed to the change)

**Comment by Rocco83** [comment]
About deleting ID:
in 6.1.6 was just not working.
Also the API state that ID is needed.
Do you have another version?

**Comment by evgeni** [comment]
Interesting. I tried this on 6.1.4, 6.1.6 and 6.1.7, works just fine.

API docs on my 6.1.7 say:
id (required) Value: Must be an identifier, string from 1 to 128 characters containing only alphanumeric characters, space, underscore(_), hypen(-) with no leading or trailing space.

It does not say it has to be the numeric id.

did you maybe try when https://github.com/sideangleside/sat6-bootstrap/pull/34 was not merged yet?

anyways, as long as it is working, I am fine :)

**Comment by Rocco83** [comment]
I recall that i tried without success, and i have concluded that id (required) must be THE id, even if i were guessing about "alphanumeric".
but let's say... as long as this if fine also for you :)
@sideangleside i have a final commit https://github.com/sideangleside/sat6-bootstrap/pull/35 that should fix the originial issue.

**Comment by evgeni** [comment]
as #35 is now merged, we can close this, right?

**Comment by Rocco83** [comment]
Yes, closed.
