### ISSUE TITLE
Fails on nested hostgroups with same name

### ISSUE THREAD

**Issue by frelind** [Katello/katello-client-bootstrap#42]
If there's more than one hostgroup with the same name but different parent it will try to use the parent hostgroup.

Example:
RHEL7/common
RHEL6/common

Script will try to use RHEL7 or RHEL6 instead.

**Comment by evgeni** [comment]
how do you call the script? `-g RHEL7/common` should work just fine.

**Comment by Rocco83** [comment]
I am using a very similar syntax (3 level nesting, "RHEL7/PROD/Rolling") and it is working properly.
+1 for @evgeni,  please share the code.

**Comment by frelind** [comment]
```
python ./bootstrap.py -l user -g "Base/RHEL7/common" -s satellite.foo.com -a "mykey" -f -L mylocation -o myorg -v

https://satellite.foo.com:443/api/v2/hostgroups/?search=title%3DBase%2FRHEL7%2Fcommon
request: https://satellite.foo.com:443/api/v2/hostgroups/?search=title%3DBase%2FRHEL7%2Fcommon
request: https://satellite.foo.com:443/api/v2/hostgroups/47
request: https://satellite.foo.com:443/api/v2/hostgroups/4/5/7
Error: cannot connect to the API: HTTP Error 404: Not Found
Check your URL & try to login using the same user/pass via the WebUI and check the error!
error: <!DOCTYPE html>
<html>
<head>
  <title>The page you were looking for doesn't exist (404)</title>
  <style type="text/css">
    body { background-color: #fff; color: #666; text-align: center; font-family: arial, sans-serif; }
    div.dialog {
      width: 25em;
      padding: 0 4em;
      margin: 4em auto 0 auto;
      border: 1px solid #ccc;
      border-right-color: #999;
      border-bottom-color: #999;
    }
    h1 { font-size: 100%; color: #f00; line-height: 1.5em; }
  </style>
</head>

<body>
  <!-- This file lives in public/404.html -->
  <div class="dialog">
    <h1>The page you were looking for doesn't exist.</h1>
    <p>You may have mistyped the address or the page may have moved.</p>
  </div>
</body>
</html>

url: https://satellite.foo.com:443/api/v2/hostgroups/4/5/7
```

`Base/RHEL7` = id 7
`Base/RHEL7/common` = id 47

Running Satellite 6.1.4

**Comment by evgeni** [comment]
Hi, yeah, that looks wrong, but I am not sure this is because of the nesting. Could you provide the output of 

```
hammer hostgroup list --org myorg
```

to allow us understand the structure better

**Comment by evgeni** [comment]
Ok, so your problem seems to be somewhere in `return_puppetenv_for_hg(hg_id)`.

Can you show the JSON returned by https://satellite.foo.com:443/api/v2/hostgroups/47 and https://satellite.foo.com:443/api/v2/hostgroups/7?

**Comment by frelind** [comment]
If I set the Puppet environment for the hostgroup instead of using inherit from parent the script works.

I will post the JSON data

**Comment by evgeni** [comment]
Yeah, I think the issue is that you have more than one inheritance layers and https://github.com/sideangleside/sat6-bootstrap/blob/master/bootstrap.py#L367 fails then.

**Comment by evgeni** [comment]
@frelind can you please try the patch at https://github.com/evgeni/sat6-bootstrap/commit/7d758bb3c05d1c1cf9e9e925e5b4393f6f97c28e?

**Comment by frelind** [comment]
@evgeni I've applied your patch and it's working great. Thank you!
