### ISSUE TITLE
Usage through proxy still uses port 443

### ISSUE THREAD

**Issue by scallywag41** [Katello/katello-client-bootstrap#43]
If you edit the python and set the API_PORT to 8443 (the reverse proxy port on the capsule back to the satellite) it will still make calls via 443.  Here is a quick cut/paste of the relevent output.

://MYCAPSULE:443/api/v2/hostgroups/?search=title%3Ddev
request: https://MYCAPSULE:443/api/v2/hostgroups/?search=title%3Ddev
Error: cannot connect to the API: HTTP Error 404: Not Found
Check your URL & try to login using the same user/pass via the WebUI and check the error!
error: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>

<h1>Not Found</h1>

<p>The requested URL /api/v2/hostgroups/ was not found on this server.</p>

</body></html>

url: https://MYCAPSULE:443/api/v2/hostgroups/?search=title%3Ddev

**Comment by Rocco83** [comment]
Hi,

in order to reproduce the problem,

```
def get_api_port():
    configparser = SafeConfigParser()
    configparser.read('/etc/rhsm/rhsm.conf')
    return configparser.get('server', 'port')
```

In main()

```
if options.remove:
    API_PORT = get_api_port()
[...]
elif check_rhn_registration():
[...]
    API_PORT = get_api_port()
[...]
else:
[...]
    API_PORT = get_api_port()
[...]
```

Which port do you have in /etc/rhsm/rhsm.conf of the specified server?

Ciao,
Daniele

**Comment by scallywag41** [comment]
```
[root@******* /]# cat /etc/rhsm/rhsm.conf | grep port
# Server port:
port = 443
# port for http proxy server
proxy_port =
```

**Comment by evgeni** [comment]
Can you provide a full bootstrap.py call and output?

rhsm.conf is provided by the katello-ca rpm which bootstrap.py installs at the very beginning. The one you get from the Capsule should have port 8443 in it.

**Comment by scallywag41** [comment]
This system may have been registered to satellite directly, then later the registration was attempted to the capsule.  When I change the line we are looking at to 8443 in /etc/rhsm/rhsm.conf things seem to work.  Thanks :)
