### ISSUE TITLE
Move this script to Katello github org 

### ISSUE THREAD

**Issue by mccun934** [Katello/katello-client-bootstrap#46]
IMO, this should be brought under the Katello umbrella and re-branded to not be Satellite specific.

Proposed new home:

https://github.com/Katello/client-bootstrap

I'm going to submit a PR to that repo with a new README + bootstrap.py that is reworded to state Katello vs Satellite and can be maintained as part of the upstream of Satellite.

**Comment by evgeni** [comment]
:+1: on moving to the Katello org, but why creating the repo from scratch instead of moving this one there? that would preserve history etc.

**Comment by mccun934** [comment]
@evgeni I'm preserving history, doing a rebase/merge from this repo.

**Comment by Rocco83** [comment]
@mccun934 also the PR will be keeped?

**Comment by mccun934** [comment]
Update:

I took what was in this repo and rebased it here:

https://github.com/Katello/client-bootstrap

it is slightly out of date and I need to get the following commits merged in:

c8e1261 Merge pull request #48 from evgeni/disassociate-before-delete
7688302 Merge pull request #45 from evgeni/multiple-ancestry-fix
8aef0e1 Merge pull request #44 from Rocco83/master
fb9d3ad Added default value to null_result_ok=False
72afdde Added default value to null_result_ok=False
b5643d6 Changed function in main() to retrieve host_id and removed unused functions
7bd0070 fixed code to be pep8 compliant, apart from line lenght
787d1c5 disassociate host from the backing VM before deleting it
a4d45a0 Removed obsolete comments, keeped same space between functions
4a3f5e8 Code cleanup, partitiontable option added
7d758bb fix fetching data from parent HG if we have multiple layers of ancestry
e8be3cb Fixed code
d6ae18f Generic get_id function, draft for partition table retrieve

@Rocco83 I don't know of an easy way to get the PRs recreated but will look into it.

**Comment by evgeni** [comment]
@mccun934 I think @sideangleside should be able to move the repo from here to katello. then issues/prs will be preserved.

**Comment by Rocco83** [comment]
Seems to me that the project has been rebased, keeping the name but under Katello. Am i correct? 
On the other side the project is not in sync with commits, but it have some other commit inside.
Next steps?

Thanks
Daniele

**Comment by mccun934** [comment]
This is now complete, you may need to rebase your PRs as we had to make this script non-Satellite specific and upstream friendly
