### ISSUE TITLE
Can Delete Virtual Machine during Re-registration attempts

### ISSUE THREAD

**Issue by scallywag41** [Katello/katello-client-bootstrap#47]
For Red Hatters please see:
CASE 01600399
bootstrap.py deletes virtual machine

I ran the script to attempt to "re-register" a system with the --force option.  Apparently, it will remove the old host entry (as it should).  However, this does not simply remove the entry, if your satellite is communicating properly with vsphere, it will also delete the etire virtual machine from vsphere.  This may be more of a function of the way sat handles removal requests then an issue with the script.  I will try to update this when/if GSS responds.

[RUNNING], [2016-03-14 16:46:48], [Deleting host id 4 for host HOST]

**Comment by evgeni** [comment]
nice catch. Satellite behaves exactly as it was asked to, but that's obviously not what we want :-)

let's see if there is a way to work around this

**Comment by evgeni** [comment]
@scallywag41 can you please try the patch at https://github.com/evgeni/sat6-bootstrap/commit/787d1c51dbef7c84ba8dbe8dbc9fa143ee6201c0?

**Comment by CalvinHartwell** [comment]
Evgeni's patch looks correct to me, the host should be disassociated first
before the delete to stop this issue.

Explanation:

The deletion of the virtual machine from vCenter is expected functionality
from this API call if the virtual machine has been associated to a compute
resource (vCenter in this case).

This REST API call performs the same action as pressing the delete action
on a host in the all hosts page.

To perform a soft delete on the host without destroying the VM, you must
first disassociate the the host before attempting to delete it. This will
remove the link from the virtual machine and the compute resource.

You may also be able to do this via Hammer.

On Tue, Mar 15, 2016 at 10:54 AM, Evgeni Golov notifications@github.com
wrote:

> @scallywag41 https://github.com/scallywag41 can you please try the
> patch at evgeni@787d1c5
> https://github.com/evgeni/sat6-bootstrap/commit/787d1c51dbef7c84ba8dbe8dbc9fa143ee6201c0
> ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/sideangleside/sat6-bootstrap/issues/47#issuecomment-196746414

##

**Comment by scallywag41** [comment]
I will have to take a look at this in the AM.  I wasn't expecting such a quick response.  Thanks :)

**Comment by scallywag41** [comment]
Well.  I pulled the python from https://github.com/evgeni/sat6-bootstrap.  However, it appears I am getting the same results (I've blown away my test host again heh).  Forgive me - I'm not a dev and so my git knowledge is more limited.  Is there a different process I should follow?

**Comment by evgeni** [comment]
Yeah, you need the version from https://github.com/evgeni/sat6-bootstrap/tree/disassociate-before-delete, direct link: https://raw.githubusercontent.com/evgeni/sat6-bootstrap/disassociate-before-delete/bootstrap.py

**Comment by scallywag41** [comment]
Thanks.  Let me rebuild and I'll try again with that :P

**Comment by CalvinHartwell** [comment]
Hey Scallywag,

I believe Evgeni created a new branch for his fixes, which needs to be
tested before making a pull request back to the original repo (
https://git-scm.com/docs/git-request-pull).

You need this file: https://github.com/evgeni/sat6-bootstrap/blob/787d1c51dbef7c84ba8dbe8dbc9fa143ee6201c0/bootstrap.py

Cheers

On Wed, Mar 16, 2016 at 3:28 PM, scallywag41 notifications@github.com
wrote:

> Thanks. Let me rebuild and I'll try again with that :P
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/sideangleside/sat6-bootstrap/issues/47#issuecomment-197354300

##

**Comment by scallywag41** [comment]
Excellent.  Thanks gentlemen.  I've re-run this a good amount of times and feel a great deal safer using it now.  If there are no objections I'll close this issue.  Two thumbs up all :)

**Comment by evgeni** [comment]
@scallywag41 thanks for testing, proposed the merge now.
