### ISSUE TITLE
get_bootstrap_rpm doesn't die in case if remote package doesn't exist

### ISSUE THREAD

**Issue by rplevka** [Katello/katello-client-bootstrap#50]
`get_bootstrap_rpm` calls `exec_failexit` on `yum localinstall` but due to way `yum` handles responses, it does not catch the failure in download of the package:

``` bash
> yum -y localinstall http://completely.fictive.hostname/foo.rpm --nogpgcheck
Loaded plugins: product-id, security, subscription-manager
Setting up Local Package Process
Cannot open: http://completely.fictive.hostname/foo.rpm. Skipping.
Nothing to do
> echo $?
0
```
- so it evaluates this situation as a success and continues.

**Comment by Rocco83** [comment]
Hi,

i have to admit that i do not know the yum internals.
Based on https://bugzilla.redhat.com/show_bug.cgi?id=753089 localinstall is totally deprecated.
Referring to https://ask.fedoraproject.org/en/question/37721/what-is-the-difference-between-yum-install-and-yum-localinstall/ seems that there are no difference between install and localinstall for "local" packages.

Are you able to check if changing the code from yum localinstall to yum install will give the expected output?

**Comment by rplevka** [comment]
@Rocco83 yes, that seems to work the same way and returns `1` which is exactly what we need

``` bash
> yum -y install http://completely.fictive.hostname/foo.rpm --nogpgcheck
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Cannot open: http://completely.fictive.hostname/foo.rpm. Skipping.
Error: Nothing to do
> echo $?
1

```

**Comment by Rocco83** [comment]
LGTM :+1: 
this is a long waiting topic, the fix is pretty straightforward. 
@mccun934 any plan on next merging?
