### ISSUE TITLE
Odd issue in return_matching_id... 

### ISSUE THREAD

**Issue by mrmattx3** [Katello/katello-client-bootstrap#52]
Greetings all,

Disclaimer would be that this is probably something missing on my RHEL7 (hooking to Sat 6.1) server.

When I run the script, I get through several of the steps and then come out with this error:

[SUCCESS], [2016-04-01 13:56:45], [/usr/bin/yum -y localinstall http://myserver.com/pub/katello-ca-consumer-latest.noarch.rpm --nogpgcheck], completed successfully.

Traceback (most recent call last):
  File "./bootstrap.py", line 426, in <module>
    create_host()
  File "./bootstrap.py", line 360, in create_host
    myorgid = return_matching_id('organizations', 'name=%s' % options.org, False)
  File "./bootstrap.py", line 317, in return_matching_id
    print_error("%d element in array for search key %s in API %s. Fatal error." % result_len, search_key, api_name)
TypeError: not enough arguments for format string

I checked to make sure I have a Host Group setup, and I put the Org in quotes to be safe (tried with an without quotes, the error is the same).  

I'm not sure what I'm missing.  

Thanks in advance,
MM

**Comment by rplevka** [comment]
could you doublecheck that `yum -y localinstall` (the very top line of the output you pasted) really succeeded in installing the rpm?
the [SUCCESS] in your log might be misleading due to this bug:
https://github.com/Katello/client-bootstrap/issues/50

not having the certificate installed might lead to errors in ID retrievals later in the script which might be your case

**Comment by mrmattx3** [comment]
I ran it manually and it came back with the following.  Assuming this means it's already there?  

_yum -y localinstall http://bogushost.domain.com/pub/katello-ca-consumer-latest.noarch.rpm --nogpgcheck
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos, subscription-manager
This system is receiving updates from RHN Classic or Red Hat Satellite.
katello-ca-consumer-latest.noarch.rpm                                                                                                                                              | 8.3 kB  00:00:00
Examining /var/tmp/yum-root-c7JY5I/katello-ca-consumer-latest.noarch.rpm: katello-ca-consumer-bogushost.domain.com-1.0-1.noarch
/var/tmp/yum-root-c7JY5I/katello-ca-consumer-latest.noarch.rpm: does not update installed package.
Nothing to do_

Hope this helps,
MM

**Comment by Rocco83** [comment]
can you please paste the full output with verbose output?

Thanks,
Daniele

**Comment by mrmattx3** [comment]
[yum_output.txt](https://github.com/Katello/client-bootstrap/files/200231/yum_output.txt)

[botstrap_log_verbose.txt](https://github.com/Katello/client-bootstrap/files/200304/botstrap_log_verbose.txt)

Files attached for both commands with -v.  I had to cleanse them a little, but this is the output. 

Thank you folks for your persistence.

**Comment by Rocco83** [comment]
My best bet, "Default Org" is not existing and you hitted a bug in handling this exception.
can you please run 
`hammer organization list`
and of course post the output?

**Comment by mrmattx3** [comment]
Interesting...  I'm masking the name here, but this is what I got.  Could the space in the name be causing the issue?

root@topjcnt-rhsat-00 bin]# hammer organization list
[Foreman] Username: xxx
[Foreman] Password for xxx:
---|--------------|--------------|------------
ID | NAME         | LABEL        | DESCRIPTION
---|--------------|--------------|------------
3  | Default Org | Default_Org |
---|--------------|--------------|------------

Is what hammer outputs...  

I tried using the API link directly, though, and both (name and label) come back with:
{
  "total": 1,
  "subtotal": 0,
  "page": 1,
  "per_page": 20,
  "search": "name=Default Org",
  "sort": {
    "by": null,
    "order": null
  },
  "results": []
}

Which is why I wonder if the space is making a difference.  Or wondering if I missed something in the Org setup?

**Comment by rplevka** [comment]
yeah, looks like it's the space in the name - this is already a known issue; i'm having a pending PR to handle this, could you possibly try to apply this change?
https://github.com/Katello/client-bootstrap/pull/49
in a nutshell, it url-encodes the org name before it passes it as an argument (so the space becomes a %20)
(you might have to change `foreman_fqdn` to `sat6_fqdn` depending on how old your script is)

**Comment by Rocco83** [comment]
:+1: i am moving to the other thread. i have some suggestion.

**Comment by Rocco83** [comment]
@mrmattx3 is "****" something you should remove in your attached file?
(removed after fix)

**Comment by mrmattx3** [comment]
Fixed.  Thanks for the heads up.

**Comment by Rocco83** [comment]
@mrmattx3 did https://github.com/Katello/katello-client-bootstrap/issues/49 fixed this issue?
If so, can you close the issue?

**Comment by evgeni** [comment]
@mrmattx3 if the current version in git is good, could you please close this issue? :)

**Comment by mrmattx3** [comment]
Apologies.  Done.
