### ISSUE TITLE
loose the hardcoded error message as it produces confusing errors

### ISSUE THREAD

**Issue by rplevka** [Katello/katello-client-bootstrap#53]
Perhaps the following lines of code should be dropped:
https://github.com/Katello/client-bootstrap/blob/master/bootstrap.py#L241-#L242
as they provide confusing output if the root cause is completely different from 'connecting to API':

e.g.:

``` bash
[RUNNING], [2016-04-05 14:29:38], [Calling Satellite API to create a host entry associated with the group, org & location] 
Error: cannot connect to the API: HTTP Error 422: Unprocessable Entity
Check your URL & try to login using the same user/pass via the WebUI and check the error!
error: {
  "error": {"id":null,"errors":{"name":["has already been taken"],"mac":["has already been taken"]},"full_messages":["Name has already been taken","MAC address has already been taken"]}
}
```

**Comment by Rocco83** [comment]
What about handling the HTTP error 401 vs 422 vs others?

**Comment by rplevka** [comment]
Sure, that would address the issue as well

**Comment by rplevka** [comment]
@Rocco83 anyway, I think dropping the 'cannot connect to the API' message would do (at least for now). The other errors seem to be self explaining.
What do you think?

**Comment by Rocco83** [comment]
@rplevka :+1: please check https://github.com/Katello/katello-client-bootstrap/issues/61

**Comment by Rocco83** [comment]
@rplevka can you check and close the issue if fixed?

**Comment by evgeni** [comment]
also #67 should help here :)

**Comment by rplevka** [comment]
This has been fixed already.
