### ISSUE TITLE
Refactoring of try/catch for API call

### ISSUE THREAD

**Issue by Rocco83** [Katello/katello-client-bootstrap#62]
We have the same code over 
get_json() https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L230 
post_json() https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L251
delete_json() https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L277.
In almost all catch.
https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L287 should probably have opposite logic, with pass instead of raise.
Refactoring can be a good idea.

**Comment by evgeni** [comment]
also, I think we should just have one "call_api" function, which can do GET, POST and DELETE. I have started something like this, will post later :)

**Comment by evgeni** [comment]
@rplevka @Rocco83 please see my first (totally untested, did not want to boot my vm) approach here: https://github.com/evgeni/sat6-bootstrap/compare/master...unify-http-requests

not sure I want to keep `ignore_404` as a parameter, it could also be unconditionally `True` if `method=='DELETE'`, and `False` otherwise.

**Comment by evgeni** [comment]
updated the code, now with nicer error formating (yay, json.dumps) and better verbose output

**Comment by rplevka** [comment]
https://github.com/evgeni/sat6-bootstrap/compare/master...unify-http-requests?diff=unified&name=unify-http-requests#diff-cd48c161c09e850299d4a00383422690R280
- is this supposed to be cooler than search+replace? :)

**Comment by evgeni** [comment]
Yeah, technically one could replace all `get_json` calls with `call_api`. I don't really mind either way, to be honest.

**Comment by rplevka** [comment]
@evgeni :+1:  on your approach. @Rocco83, could we get your opinion, please?

**Comment by evgeni** [comment]
thanks @rplevka 

dropped the `ignore_404` part as discussed on IRC, we are not going to try to delete non-existant hosts since 4967bc1c222e14bee887c480616f174582d3b176

**Comment by Rocco83** [comment]
Sorry for the delay.
Seems good to me, still i have not tested the code.

I have made a comment on 
https://github.com/evgeni/sat6-bootstrap/commit/f764a170532d1fe01e4a103e29b5c587693d9b67?diff=split#diff-cd48c161c09e850299d4a00383422690R259
because the API can be foreman or katello :)

Anyway this is a very good improvement 👍
