### ISSUE TITLE
[RFE] Add support for removing RHUI Packages

### ISSUE THREAD

**Issue by sideangleside** [Katello/katello-client-bootstrap#64]
I want to add support for removing packages that provide access to repositories hosted by RHUI (which is used by various cloud providers, such as Amazon). There are two ways I am thinking of tackling this:
- Add a new switch (--remove-rhui-packages), which calls 'yum remove rh-_-rhui-client_' 
- refactoring the (-R | --remove-rhn-packages) switch (and associated function), to make a generic (-R | --remove-packages) switch, which removes both the RHN & RHUI packages. 

Also, what are your thoughts on defaulting to removing the old RHN & RHUI packages (Today we only remove them if explicitly asked)?

**Comment by evgeni** [comment]
Removing RHUI packages sounds sane, yeah. I think we should call the option `--remove-obsolete-packages` and keer `--remove-rhn-packages` as an deprecated alias.

And yes, removing cruft by default sounds sane too. Keeping them would then go via `--remove-obsolete-packages=no`?

**Comment by Rocco83** [comment]
👍 on evgeni.

**Comment by evgeni** [comment]
@sideangleside there, please test :-)
