### ISSUE TITLE
RHEL5 support

### ISSUE THREAD

**Issue by Rocco83** [Katello/katello-client-bootstrap#65]
Hi,

I am testing finally the script on some RHEL5, python 2.4.

Got, up to now, the following problems:
- json python non existing.
  Solution: http://stackoverflow.com/questions/3291682/json-module-for-python-2-4
  Status: Tested, working
- sys.maxsize non existing.
  Solution: http://stackoverflow.com/questions/1405913/how-do-i-determine-if-my-python-shell-is-executing-in-32bit-or-64bit-mode-on-os
  Status: testes only on command line, seems working
- platform.linuxdistribution non existing
  Solution: https://docs.python.org/2/library/platform.html#platform.linux_distribution we can use platform.dist on old systems
  Status: Briefly tested, working

In order to get the version and understand which code to be run, in example for platform.linuxdistribution,
https://docs.python.org/2/library/sys.html#sys.hexversion
or
http://stackoverflow.com/questions/1093322/how-do-i-check-what-version-of-python-is-running-my-script

patch coming soon, this has been not tested deeply.

**Comment by evgeni** [comment]
I have a long standing branch on this: https://github.com/evgeni/sat6-bootstrap/tree/rhel5
never merged, though

**Comment by Rocco83** [comment]
Well, shame on me... i have not checked the fork :)
Discussing about the code:
- 64 bit check

yours https://github.com/Katello/katello-client-bootstrap/compare/master...evgeni:rhel5?expand=1#diff-cd48c161c09e850299d4a00383422690R25
mine https://github.com/Katello/katello-client-bootstrap/pull/66/commits/e0469f3eadd16a3813db96738898fad736ae465d#diff-cd48c161c09e850299d4a00383422690R25
Your approach is cleaner, mine is more general (but maybe not needed)
- platform.linux_distribution

yours https://github.com/Katello/katello-client-bootstrap/compare/master...evgeni:rhel5?expand=1#diff-cd48c161c09e850299d4a00383422690R56
mine https://github.com/Katello/katello-client-bootstrap/pull/66/commits/e0469f3eadd16a3813db96738898fad736ae465d#diff-cd48c161c09e850299d4a00383422690R48
Your approach do not take care of the version, which can be good. mine is stricter as approach, and may lead to some bugs.
- json

your https://github.com/Katello/katello-client-bootstrap/compare/master...evgeni:rhel5?expand=1#diff-cd48c161c09e850299d4a00383422690R513
mine https://github.com/Katello/katello-client-bootstrap/pull/66/commits/e0469f3eadd16a3813db96738898fad736ae465d#diff-cd48c161c09e850299d4a00383422690R3
Well, i have checked over the history and i have seen that you have first made my same commit and than changed it. So your code is better, absolutely.

You also fixed something else like the 
- mac address: https://github.com/Katello/katello-client-bootstrap/compare/master...evgeni:rhel5?expand=1#diff-cd48c161c09e850299d4a00383422690R35
- puppet conf: https://github.com/Katello/katello-client-bootstrap/compare/master...evgeni:rhel5?expand=1#diff-cd48c161c09e850299d4a00383422690R238
- rhel5 migration: https://github.com/Katello/katello-client-bootstrap/compare/master...evgeni:rhel5?expand=1#diff-cd48c161c09e850299d4a00383422690R477

Maybe you can review my previous points and decide if import/change part of code... But not needed at all.

Conclusion: since the code can be pushed immediately, if you want to make a pull request, i think that your code is much better and more tested 👍

**Comment by evgeni** [comment]
64bit check was taken as an idea from https://docs.python.org/2/library/platform.html#platform.architecture
checking `sizeof(void *)` as you do should work too, yeah. I don't really mind either.

distribution: both should work, so I don't care which we take :)

json: the idea is that we try to install python-simplejson if that is not available (yet), and I'd prefer that.

the code was tested by @MartijntenHeuvel, as I thankfully don't have many RHEL5 boxes
maybe he or @sideangleside want to chime in too? :)

**Comment by Rocco83** [comment]
Good, 
@evgeni can you please create a PR in the meaintime?
I have closed mine.

**Comment by evgeni** [comment]
@Rocco83 done :)
