### ISSUE TITLE
release is not used

### ISSUE THREAD

**Issue by evgeni** [Katello/katello-client-bootstrap#73]
`register_systems(org_name, activationkey, release)` gets a `release` parameter but does not use it (that was removed in b63a0cea7f25b29d7a25f610d680da61b80e0f41).

also, while at it, the RHEL5 check probably should use `options.release` in https://github.com/Katello/katello-client-bootstrap/blob/master/bootstrap.py#L495

**Comment by peppos** [comment]
@evgeni I confirm you that "option.release" correctly work  in RHEL5

**Comment by soukron** [comment]
https://github.com/Katello/katello-client-bootstrap/pull/205 to fix this. I faced the problem today and it's straight forward to add it.

This was my scenario to reproduce it:
 1 create a CV with RHEL 7.3 repository (not RHEL 7Server)
 2 boot a RHEL 7.3 VM and subscribe it manually and run yum clean && yum repolist
    2.1 repos URL use /7Server/ in their release part which is not in the CV
 3 use subscription-manager release --set 7.3 and run yum clean && yum repolist
    3.1 repos URL use /7.3/ in their release part, which is correct
 4 use bootstrap.py to register the server again without --release
    4.1 katello-agent installation fails because 2.1
 5 use bootstrap.py to register the server again but use --release 7.3
    5.1 katello-agent installation fails because --release is not set at registration time, so 2.1 again

**Comment by soukron** [comment]
Also note that I know the fact that the activation kay may also set the release, but given the existence of the parameter I'd prefer to be able to use it to force different releases and not being forced to create multiple activation keys.

**Comment by sideangleside** [comment]
Should we be even allowing users to override the release version of their activation keys?. When using multiple activation keys, you have to contend with the behavior of multiple activation keys (the key that is the furthest to the right (on the CLI) wins), and now you are giving the user the ability to override that. That implies that the admin bootstrapping the client is smarter than the activation key, which seems incorrect. 

Most of the `bootstrap.py` options either 

- Provide data that is required that isn't provided by the server (such as the server URL, Org, Location, Operating system)  **OR**
- Change the behavior of the script itself. (like the --skip options, --install-packages, etc)

This plus the fact that `rhn-migrate-classic-to-rhsm` doesnt support `--release`, I am in the camp that we shouldn't implement it.

**Comment by soukron** [comment]
Yeah, that's another option: get rid of the parameter, but then you're forcing the users to create multiple activation keys instead of just allowing to override by using a method provided by subscription-manager itself. 

IMHO it's useful, but I don't have any other killer argumentation than my experience as user by patching the file with every single Satellite installation I made to make it work as expected.

What about setting a release (according to parameter) AFTER subscribing? I mean, not adding the parameter at registration time (so we don't override the AK) but running a subscription-manager release --set options.release before installing any other package?

The result would be the same (package installation doesn't fail) but you may like it more.

**Comment by evgeni** [comment]
I think I now remember/recognize why we removed that.

We read the release version using Python's `platform` module, and that will always return the full release number (7.4, 6.9, etc) and never the XServer (6Server, 7Server) one. However, Katello might only server the 7Server one in the content view.

If we now would force the `--release` param of subscription-manager, we would end up with invalid repo URLs, as the release is part of the URL.

If we ditch the code guessing the release, and only pass `--release` when the user passed it to us, that would work, I guess.

**Comment by soukron** [comment]
That's the idea: let a user set a different release so katello-agent and other packages won't fail.

As said, is you prefer to change the implementation is okay for me as both options do the job:
 - using --release in the subscription-manager register command, if the option is passed
 - run an extra subscription-manager release to set the release, if the option is passed

The first may be better from @sideangleside point of view by not overriding the activation key default behaviour but subscription-manager executions are sometimes slow and we're doing it twice when just one is enough.

**Comment by sideangleside** [comment]
The only way (that I can think of) that setting the releasever via bootstrap.py makes sense is if you have multiple release versions of content (7Server + 7.3) in a content view, and you don't necessarily want to use (at least 2) activation keys.  I personally wouldn't construct my content views that way, but that is a matter of implementation and the tools don't stop you from doing i so I say we should support it. (Yes, I am changing my mind from my above statement)

I think we'd need to do both of @soukron's proposals. In the `register_systems` function, we'd need to 'using --release in the subscription-manager register command, if the option is passed'. 

In `migrate_systems`, we'd need to 'run an extra subscription-manager release to set the release, if the option is passed' as `rhn-migrate-classic-to-rhsm` doesnt support `--release`

The only thing that I'd want to confirm (now paging @jlsherrill :) ) is if a specific release version is passed to `subscription-manager` at registration time (via `--releasever`), does it override what is specified on the activation key(s)? I am pretty sure it does, but I'd want to confirm.

**Comment by soukron** [comment]
Thanks for your understanding @sideangleside. 

I wouldn't make the CVs that way also, but I'm seeing a lot of people doing this: Publish a CV with 7Server repositories but use it for different systems with a fixed version (ie 7.2), having just one AK which sets the release to 7Server by default. They just fix the release from the client to the desired one, they still get erratas until they're published and the upgrade to next minor is as easy as setting a different release and running yum update. Doesn't sound that bad.

Regarding the activation key being overrided, I confirmed during my tests that it works as expected, but let's wait for @jlsherrill double confirmation.

**Comment by jlsherrill** [comment]
I confirmed the behavior (its happening completely in candlepin).  I think providing this option for the user to specify makes perfect sense!
