### ISSUE TITLE
Does not work with foreman locations disabled

### ISSUE THREAD

**Issue by gorantornqvist** [Katello/katello-client-bootstrap#74]
When omitting the -L parameter I get a 404 from API url /api/v2/locations/?search=title%3DDefault_Location

Would be nice to be able to use the script without locations enabled ...

**Comment by evgeni** [comment]
true. patches welcome? :-)

from a quick glance at the code, we would have to:
- make `--location` optional
- in `create_host()` only lookup `mylocid` if `options.locations` is not `None`
- in `create_host()` only add `location_id` to `jsondata` if `options.locations` is not `None`
- in `create_host()` adjust the printed message

does not seem to bad/complicated?

**Comment by evgeni** [comment]
@gorantornqvist can you please test https://github.com/evgeni/sat6-bootstrap/tree/drop-location-dependency? this _should_ do what you want, but is untested ;-)

**Comment by evgeni** [comment]
@gorantornqvist ping? :-)

**Comment by gorantornqvist** [comment]
Sorry, I didnt see the emails. I will test the script tomorrow...

**Comment by evgeni** [comment]
no worries, take your time, just wanted to make sure that you are actually about to test it ;-)

**Comment by gorantornqvist** [comment]
Hi, 
I don´t get the location error anymore, although I get this error on my Satellite 6.1.9 which is something different.

[RUNNING], [2016-06-08 09:05:12], [Calling Foreman API to create a host entry associated with the group & org] 
Error: The following error occured while talking to the API:
url: https://satellite:443/api/v2/hosts/
code: 422
`
data: {
  "host": {
    "managed": "true", 
    "name": "myhost", 
    "hostgroup_id": 47, 
    "organization_id": 1, 
    "mac": "00:50:56:A4:XX:XX", 
    "architecture_id": 1, 
    "domain_id": 1
  }
}
error: {
  "error": {
    "errors": {
      "ip": [
        "is invalid"
      ]
    }, 
    "id": null, 
    "full_messages": [
      "IP address is invalid"
    ]
  }
}
`

I have no IPAM or DNS/DHCP capsule in my setup, we set IP manually for bare-metal and VMware orchestration sets the host IP using a similar API call as above when it creates VMs.
So not sure if this error has something to do with my setup ...

**Comment by evgeni** [comment]
Hi @gorantornqvist,

great that you are over the hill and up to the next issue :-)

Does the hostgroup you are trying to deploy into (id=47) have a default subnet set? And if it does, what are the settings of that subnet? I had a similar issue some time ago in my tests, and the issue was that the subnet had some bad settings (can't remeber which exactly, but can look up later if you want).

**Comment by gorantornqvist** [comment]
No, I have no subnet set on the hostgroup since we don´t use subnets in Satellite 6. Tried to create a dummy subnet with all network settings and assign it to the hostgroup but same error occurrs. So I don´t think I can leave IP out I´m afraid.

Its no biggie though, I was just looking for the best way to migrate a bulk of RHEL6 hosts to Satellite later this year. We can also use our home made satellite-register shell script to do this...not as elegant though :)

Thanks for your help ...

**Comment by evgeni** [comment]
@gorantornqvist can you try with `--unmanaged` please?

**Comment by gorantornqvist** [comment]
with --unmanaged it registered fine, thanks...:)
