### ISSUE TITLE
does not work on i386

### ISSUE THREAD

**Issue by evgeni** [Katello/katello-client-bootstrap#82]
`ARCHITECTURE` is either `x86` or `x86_64` but the archs are called `i386` and `x86_64`…

spotted while reviewing @lzap's code

**Comment by lzap** [comment]
> `ARCHITECTURE` is either `x86` or `x86_64` but the archs are called `i386` and `x86_64`…
> 
> spotted while reviewing @lzap's code

Yeah that is not correct, architecture can be arbitrary string, but with
the initial puppet fact upload new architecture i386 will be created and
associated with the host. Facter simply uses uname, I was checking this.

## 

Later,
 Lukas #lzap Zapletal

**Comment by evgeni** [comment]
fixed by @lzap in b0c4afca25a1c5b46d7d47f8de11acf365d5a3e9, thanks
