### ISSUE TITLE
When using the --skip-foreman switch we should not prompt for username/pasword.

### ISSUE THREAD

**Issue by sideangleside** [Katello/katello-client-bootstrap#86]
If I wanted to use bootstrap.py and only register the system for content via katello, I'd want to issue

```
bootstrap.py --skip-foreman -a My_Activation_Key -o My_Org -s satellite.example.com.
```

However, this command prompts me for password. 
As newer Katello versions (3.0+) have [Unified Hosts](http://www.katello.org/docs/3.0/release_notes/release_notes.html), we no longer need to create the host in Foreman so that the host / content-host entry are properly linked. 

We'd still need to create the host when setting up a host to be properly managed via Puppet. 

Having this capability makes it easier for users who are 'content-only' to get up and running, and would give them a better experience than just running 'subscription-manager register' 

**Note**: for older versions of Katello (<2.4) we'd still need to prompt for username/password to precreate the Host entry.

**Comment by evgeni** [comment]
So you want something like 2cde7cf? To be honest, `--skip-foreman` was designed exactly for that: don't need an API user. I have no clue why this slipped my tests. Or maybe I just passed `-p blah` as I knew it's unused.

**Comment by sideangleside** [comment]
Yes. https://github.com/Katello/katello-client-bootstrap/commit/2cde7cfbe9934cec542ea5364c22d5296d5884cb does exactly what we need.
