### ISSUE TITLE
[RFE] Provide bootstrap on capsules via reverse proxy

### ISSUE THREAD

**Issue by bergsjoh** [Katello/katello-client-bootstrap#96]
Keep a single place for the bootstrap.py file. For example if its located in the /usr/share/foreman/public directory, it will be available on capsules as https://<capsule>:8443/bootstrap.py via the reverse proxy.

This way it doesn't need to be managed and under control on every capsule in the infrastructure.

**Comment by sideangleside** [comment]
The bootstrap is unique **per** Satellite/Capsule, hence why it is retrieved from the hostname that the user specified.

**Comment by bergsjoh** [comment]
Ah okay. In my design/infrastructure it's common over all sat/capsules, easier to keep it managed in a single place. Our solution is to provide bootstrap via reverse proxy on capsules.

**Comment by evgeni** [comment]
@sideangleside why is it unique? it's just the file coming from the RPM, nothing special/generated (in contrast to Sat5, iirc)

**Comment by sideangleside** [comment]
Rereading the comment above, I realized that I made an incorrect statement. The bootstrap script (bootstrap.py) is the exact same on each Satellite/Capsule. The **katello-ca-consumer-latest.noarch.rpm** package (occasionally referred to as the 'bootstrap rpm') _is_ unique per Satellite/Capsule. 

My apologies.

**Comment by Rocco83** [comment]
If capsules are used for segregation of the network, the client need to retrieve somehow the bootstrap.py file.
the reverse proxy seems to me a robust solution.

also the possibility to use the latest bleeding edge version of this software can be an extension of this RFE.

my 2 cents
Daniele

**Comment by sideangleside** [comment]
The reverse proxy on the Capsule already proxies back to the upstream Katello/Satellite.

From `/etc/httpd/conf.d/28-katello-reverse-proxy.conf`:

~~~
  ## Proxy rules
  ProxyRequests Off
  ProxyPreserveHost Off
  ProxyPass / https://satellite.example.com/
  ProxyPassReverse / /
  ProxyPassReverse / https://satellite.example.com/
~~~

And you can verify this via curl:

~~~
curl -k https://capsule-1.example.com:8443/pub/bootstrap.py
~~~

I would state that this capability already exists.

**Comment by bergsjoh** [comment]
Yes, it works like I suggested now. But it wasn't back when I opened it. Magic! :)
