### ISSUE TITLE
[RFE] Make katello-ca-consumer rpm download over https

### ISSUE THREAD

**Issue by bergsjoh** [Katello/katello-client-bootstrap#97]
Reduce the requirements of firewall openings even more.

Keeping port 80 opened to capsule/satellite as a requirement just to download the bootstrap from clients seems a bit unnecessary.

**Comment by sideangleside** [comment]
RPM uses **libcurl** underneath the hood if I remember corectly. I don't know if we can teach it the equivalent of **curl -k**. That being said, I am definitely +1 to using HTTPS anywhere and everywhere. Though we'd not be able to completely remove the port 80 requirement as the Red Hat family OS's require it for kickstart. (RHEL7 _can_ do HTTPS, but it is not enabled in the provisioning templates)

**Comment by bergsjoh** [comment]
OK. In my infra we have added a separate filedownloader function to bootstrap that doesn't care about the certificate warning over https. We use that to download the rpm over https.

We don't use provisioning yet, but I will look into it in the future, and in the design we are planning to have separate provisioning capsules for that, they will have to have separate firewall openings then I guess.

**Comment by evgeni** [comment]
+1, just run into the same issue.

from a quick glance at RPM docs, I see no way to pass curl's -k to it :(

filedownloader would work, but is kinda ugly :(

**Comment by Rocco83** [comment]
If i have got the problem
1) we have to download an rpm to setup katello
2) to download the rpm we use rpm directly
3) the certificate of katello is not yet available
here we have the issue.

Is this correct?
If so, another possible way to fix it is to download and hash the ca certificare of katello correct, before the download of the rpm, correct?

**Comment by sideangleside** [comment]
I did some research into this. from `curl(1)`

~~~
curl tries to find the "home dir": It first checks for the CURL_HOME 
and then the HOME environment variables. Failing that, it uses getpwuid() 
on Unix-like systems (which returns the home dir given the current user in your system).
~~~

This applies to both the binary and libcurl implementation. 

~~~
mkdir ~/bootstrap-temp/
echo 'insecure' >> ~/bootstrap-temp/.curlrc
export CURL_HOME = ~/bootstrap-temp/
~~~

running bootstrap (and changing the 'rpm -Uvh http' to 'rpm -Uvh https') works without issue after doing such. We _could_ write to ~/.curlrc, but I dont want to clobber or change a user's existing configuration.

**Comment by evgeni** [comment]
I'd use a proper tempdir, but other than that this sounds like a quite clever solution. :+1:

**Comment by sideangleside** [comment]
Well yeah, the above was an example. I'd use a proper tempdir cause writing stuff in people's homedir is frowned upon :)
