### ISSUE TITLE
get_bootstrap_rpm() exits in case the ca-consumer package already installed

### ISSUE THREAD

**Issue by rplevka** [Katello/katello-client-bootstrap#98]
After addressing https://github.com/Katello/katello-client-bootstrap/issues/50 we exit the bootstrap script on finding out the package is already installed

```
[RUNNING], [2016-07-20 18:02:17], [rpm -Uvh http://my-katello.com/pub/katello-ca-consumer-latest.noarch.rpm] 
[ERROR], [2016-07-20 18:02:17], EXITING: [rpm -Uvh http://my-katello.com/pub/katello-ca-consumer-latest.noarch.rpm] failed to execute properly.
Retrieving http://my-katello.com/pub/katello-ca-consumer-latest.noarch.rpm
Preparing...                          ########################################
    package katello-ca-consumer-my-katello.com-1.0-1.noarch is already installed
```

We can replace the installed package easily by adding `--replacepkgs` to the `rpm` command, however I won't post a PR until we decide we want this.

Exiting the bootstrap script on finding some version of this package installed might be a wanted behavior - what do you think?

**Comment by rplevka** [comment]
totally forgot we already have `--force` option implemented which takes care of this. Closing the issue (sorry)

**Comment by evgeni** [comment]
@rplevka as this is not the first time people stumble over this non-issue, maybe we should improve our docs here?

**Comment by rplevka** [comment]
@evgeni - i think the help sommand says it all. This is purely a problem with a user :)
